--- 
pool:
  name: default
trigger:
  - master
steps: 
  - task: DotNetCoreInstaller@1
    inputs:
      packageType: 'sdk'
      version: '8.0.3'
    packageType: 'sdk'
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: false
      projects: '/src/Presentation/Nop.Web.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
      zipAfterPublish: true
