--- 
pool:
  name: default
trigger:
  - master
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.3'
steps:
  - script: dotnet --list-runtimes
    displayName: dotnet version
    continueOnError: true
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: false
      projects: '/src/Presentation/Nop.Web.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
      zipAfterPublish: true
